[tool.poetry]
name = "recommend"
version = "0.1.0"
description = "Recommendation API"
authors = ["You <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
libs-common = { path = "./libs/common" }
uvicorn = "*"

[tool.poetry.group.base.dependencies]
# Inherit from root

[tool.poetry.group.spark.dependencies]
# Inherit from root

[tool.poetry.group.dev.dependencies]
# Inherit from root
